export const mockAssets = [
    {
        asset_id: 1,
        name: 'asset1',
        kokans: 3,
        creator: 'user_id',
        created: 'DD/MM/YYYY',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
    {
        asset_id: 2,
        name: 'asset2',
        kokans: 5,
        creator: 'user_id',
        created: 'DD/MM/YYYY',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
    {
        asset_id: 3,
        name: 'asset3',
        kokans: 1,
        created: 'DD/MM/YYYY',
        creator: 'user_id',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
    {
        asset_id: 4,
        name: 'asset4',
        kokans: 3,
        created: 'DD/MM/YYYY',
        creator: 'user_id',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
    {
        asset_id: 5,
        name: 'asset5',
        kokans: 5,
        created: 'DD/MM/YYYY',
        creator: 'user_id',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
    {
        asset_id: 6,
        name: 'asset6',
        kokans: 1,
        created: 'DD/MM/YYYY',
        creator: 'user_id',
        owners: ['user_id', 'user_id'],
        broker: ['user_id'],
        type: ['code', 'web-app'],
        description_short: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        description_long: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Soluta nisi saepe ea ducimus. Commodi quisquam, ullam unde quaerat nesciunt optio accusantium dicta ea quam ex alias nisi quibusdam sint in?',
        licence: 'MIT'
    },
]

export interface AssetInterface {
    _id: string,
    title: string,
    kokans: number,
    created: string,
    creator: string,
    owners: [string],
    onOffer: boolean,
    type: [string],
    description_short: string,
    description_long: string,
    licence: string,
    aliases: {owners: [string], creator: string}
  }